## -*- encoding: utf-8 -*-
## This file (model.sagetex.sage) was *autogenerated* from model.tex with sagetex.sty version 2021/10/16 v3.6.
import sagetex
_st_ = sagetex.SageTeXProcessor('model', version='2021/10/16 v3.6', version_check=True)
_st_.endofdoc()
