name: Build Documentation and Examples

on:
  push:
    branches:
      - main

env:
  TAG: ghcr.io/abnt-latex/texlive-r
  VERSION: latest

jobs:
  build:
    name: Build Documentation and Examples
    runs-on: ubuntu-latest
    steps:
      - name: Confira o c칩digo do reposit칩rio
        uses: actions/checkout@v5
      - name: Compilando os arquivos na Docker
        run: docker run --rm -v ${{ github.workspace }}/:/content --workdir /content --entrypoint ./build.sh ${{ env.TAG }}:${{ env.VERSION }}
      - run: mkdir -p output
      - run: cp abntlatex.pdf output/
      - name: Listar arquivos dentro do reposit칩rio
        run: |
          ls -a ${{ github.workspace }}
          ls -a ${{ github.workspace }}/output
      - name: Verficar arquivo pdf
        run: |
          file output/abntlatex.pdf | grep -q ' PDF '
      - name: Carregar arquivos est치ticos como artefato
        id: deployment
        uses: actions/upload-pages-artifact@v4
        with:
          path: output
  deploy:
    if: ${{ github.repository_visibility == 'public' }}
    name: Deploy no Github Pages
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy no Github Pages
        id: deployment
        uses: actions/deploy-pages@v4